/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as FuturesRouteImport } from './routes/futures'
import { Route as LaunchpadRouteImport } from './routes/launchpad'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as NewsRouteImport } from './routes/news'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as TradePairRouteImport } from './routes/trade.$pair'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturesRoute = FuturesRouteImport.update({
  id: '/futures',
  path: '/futures',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchpadRoute = LaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TradePairRoute = TradePairRouteImport.update({
  id: '/trade/$pair',
  path: '/trade/$pair',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/earn': typeof EarnRoute
  '/fees': typeof FeesRoute
  '/futures': typeof FuturesRoute
  '/launchpad': typeof LaunchpadRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/security': typeof SecurityRoute
  '/trade/$pair': typeof TradePairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/earn': typeof EarnRoute
  '/fees': typeof FeesRoute
  '/futures': typeof FuturesRoute
  '/launchpad': typeof LaunchpadRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/security': typeof SecurityRoute
  '/trade/$pair': typeof TradePairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/earn': typeof EarnRoute
  '/fees': typeof FeesRoute
  '/futures': typeof FuturesRoute
  '/launchpad': typeof LaunchpadRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/security': typeof SecurityRoute
  '/trade/$pair': typeof TradePairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/earn'
    | '/fees'
    | '/futures'
    | '/launchpad'
    | '/login'
    | '/markets'
    | '/news'
    | '/register'
    | '/security'
    | '/trade/$pair'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/earn'
    | '/fees'
    | '/futures'
    | '/launchpad'
    | '/login'
    | '/markets'
    | '/news'
    | '/register'
    | '/security'
    | '/trade/$pair'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/earn'
    | '/fees'
    | '/futures'
    | '/launchpad'
    | '/login'
    | '/markets'
    | '/news'
    | '/register'
    | '/security'
    | '/trade/$pair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  EarnRoute: typeof EarnRoute
  FeesRoute: typeof FeesRoute
  FuturesRoute: typeof FuturesRoute
  LaunchpadRoute: typeof LaunchpadRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  NewsRoute: typeof NewsRoute
  RegisterRoute: typeof RegisterRoute
  SecurityRoute: typeof SecurityRoute
  TradePairRoute: typeof TradePairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futures': {
      id: '/futures'
      path: '/futures'
      fullPath: '/futures'
      preLoaderRoute: typeof FuturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launchpad': {
      id: '/launchpad'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof LaunchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$pair': {
      id: '/trade/$pair'
      path: '/trade/$pair'
      fullPath: '/trade/$pair'
      preLoaderRoute: typeof TradePairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  EarnRoute: EarnRoute,
  FeesRoute: FeesRoute,
  FuturesRoute: FuturesRoute,
  LaunchpadRoute: LaunchpadRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  NewsRoute: NewsRoute,
  RegisterRoute: RegisterRoute,
  SecurityRoute: SecurityRoute,
  TradePairRoute: TradePairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
